server:
  port: 8103

spring:
  application:
    name: serverPro

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka
    registerWithEureka: true
    fetchRegistry: true
  instance:
    # 客户端发送时间间隔
    lease-renewal-interval-in-seconds: 1
    # 服务端接收到最后一次心跳等待时间
    lease-expiration-duration-in-seconds: 2
